# Site settings
title: InsAIght
logo: assets/img/insaight.png # optional
tagline: Impactando a Saúde com Inteligência Artificial
description: > # this means to ignore newlines until "baseurl:"
  Uma nova era de avaliações pré-operatórias. Mais segurança, eficiência e insights baseados em dados.
repository: Vianest-iTec/vianest-itec.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://insaightmedtech.com/" # the base hostname & protocol for your site
author: Copyright &copy; 2024-2024 InsAIght Medtech Soluções Médicas LTDA
lang: pt_BR

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
